server:
  port: 31010
  servlet:
    context-path: /mgr/jvs-aps
spring:
  application:
    name: jvs-aps
  redis:
    host: 192.168.2.11
    port: 6379
    timeout: 10000
    database: 2
    password: Passw0rd
  datasource:
    url: jdbc:mysql://192.168.2.11:3306/jvs-aps?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: Passw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource


# 日志配置
logging:
  config: classpath:logback-spring.xml
  level:
    #自定义第三方包名日志等级
    # 解除注释后Druid连接池打印SQL语句
    druid.sql.Statement: debug
    druid.sql.DataSource: debug
    druid.sql.Connection: debug
    druid.sql.ResultSet: debug
log:
  level:
    # 等级 TRACE,DEBUG,INFO,WARN,ERROR(不区分大小写)
    root: INFO
  path: log/${spring.application.name}



mybatis-plus:
  configuration:
    cache-enabled: true
  global-config:
    db-config:
      logic-delete-field: delFlag
