server:
  port: 31010
  servlet:
    context-path: /mgr/jvs-aps
spring:
  application:
    name: jvs-aps
  redis:
    host: localhost
    port: 6379
    timeout: 10000
    database: 2
    password: redis
  datasource:
    url: jdbc:mysql://localhost:3306/jvs-aps?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource


#日志配置
logging:
  #使用logstash方式日志传递
  config: classpath:logback-logstash.xml
  level:
    org.springframework.web.client.RestTemplate: DEBUG



mybatis-plus:
  configuration:
    cache-enabled: true
  global-config:
    db-config:
      logic-delete-field: delFlag
